### ISSUE TITLE
random crash and hang in option --zmax>1 when nested jar has a decompression error

### ISSUE THREAD

**Issue by mmyjona** [Genivia/ugrep#313]
Given the following folder structure, ugrep may segmentation fault or deadlock when using with -z and -r arg.

```
  --root folder (pwd)
    |-- a.jar
           |-- b.jar （within a.jar） 
    |-- b.jar
```

when decompress the jar file, following warning log indicated there are potential rc:

ugrep: warning: cannot decompress b.jar: a zlib decompression error was detected in the zip compressed data
ugrep: warning: cannot decompress b.jar: EOF detected in the zip compressed data

**Comment by genivia-inc** [comment]
Looks like a decompression failure for some reason that triggers a more severe problem (hang) afterwards. I'm not convinced it is a rc problem.

More information is needed. What are all of the options you've used? Do you use `--zmax=2` to search nested zip/jar files? How many threads (try `-J1` to run with one thread) cause the problem? What decompression libraries were linked (`ug --version` shows a list of libs).

**Comment by mmyjona** [comment]
the full command is:
```
ugrep -a -z --zmax=2 -r "xxx" .
```

the -J1 doesn't make the hanging and segmentation fault go away.

version is 4.3.2 for macosx installed with homebrew:
```
ugrep 4.3.2 x86_64-apple-darwin23.0.0 +avx2; -P:pcre2jit; -z:zlib,bzip2,lzma
License: BSD-3-Clause;  ugrep user guide:  https://ugrep.com
Written by Robert van Engelen and others:  https://github.com/Genivia/ugrep
Ugrep utilizes the RE/flex regex library:  https://github.com/Genivia/RE-flex
```

**Comment by mmyjona** [comment]
here is the backtrace when it segmentation fault
![image](https://github.com/Genivia/ugrep/assets/1235078/dda9377b-495b-4583-b78a-45dd2816db9e)

**Comment by genivia-inc** [comment]
Thanks for sharing the details and trace!

I'm surprised that zlib crashes there. After the last `inflate()` call that returns an error, we still need to call `inflateEnd()` to [release zlib memory](https://refspecs.linuxbase.org/LSB_3.0.0/LSB-Core-generic/LSB-Core-generic/zlib-inflateend-1.html) and [also see here](https://www.zlib.net/manual.html). We should not just return from `decompress()`, since that may result in zlib memory leaks. Note that setting `zend_ = true` prevents further `inflate()` calls when we're done decompressing or when an error occurred, upon which we call `inflateEnd()`. If `inflateEnd()` crashes, that would be bad.

**Comment by genivia-inc** [comment]
In addition, `Zthread::start()` ugrep.cpp:814 should do the same:
~~~
      if (thread.joinable())
      {
        // wake decompression thread
        pipe_zstrm.notify_one(); // wake thread waiting in close_wait_zstream_open(), there is work to do
        pipe_ready.notify_one(); // wake thread waiting in wait_pipe_ready(), when it encountered an error
      }
~~~
This prevents a hang when something went wrong in the decompression thread, which continues to run looking for a new open pipe with other data to decompress.

**Comment by genivia-inc** [comment]
I've committed a src/ugrep,cpp update to build and test.

**Comment by mmyjona** [comment]
I pulled your recovery fixes in ugrep.cpp and reverted the early return modifications. 
Then I added some log to see if inflateEnd is called after sub-zero ret code.

```
            if (ret != Z_OK && ret != Z_STREAM_END && ret != Z_BUF_ERROR)
            {
              cannot_decompress(pathname_, "a zlib decompression error was detected in the zip compressed data");
              num = -1;
              zend_ = true;
              if (ret < Z_OK) {
                std::cout << "crsh 1" << "\n";
//                return false;
              }
            }
```
Then I add some log to the inflateEnd call
```
          if (zend_)
          {
            std::cout << "before inflateEnd" << pathname_  << num << "\n";
            ret = inflateEnd(z_strm_);
            std::cout << "after inflateEnd" << pathname_   << num  << "\n";
            if (ret != Z_OK)
            {
              cannot_decompress(pathname_, "a zlib decompression error was detected in the zip compressed data");
              num = -1;
              if (ret < Z_OK) {
                return false;
              }
            }
          }
```

I can still reproduce the hang and here is the log:
```
crsh 1
before inflateEnb.jar
after inflateEnb.jar
before inflateEnd/Users/xxx/src/test_repo/t/t2/a.jar
after inflateEnd/Users/xxx/src/test_repo/t/t2/a.jar
ugrep: warning: cannot decompress a.jar: a zlib decompression error was detected in the zip compressed data
（hang）
```

**Comment by mmyjona** [comment]
I found where it hung:
```cpp
ugrep.cpp:1204
            if (is_selected && !drain && write(pipe_fd[1], buf, static_cast<size_t>(len)) < len)

```
the write call never return.

**Comment by mmyjona** [comment]
after adding some log to multiple cv statements, I get following log:

```
failed run:

wait_pipe_ready after wait
wait_pipe_ready after wait
wait_pipe_ready wait
wait_pipe_ready wait
wait_pipe_ready after wait
wait_pipe_ready after wait
close_wait_zstream_open wait
start pipe_zstrm notify_one
ugrep: warning: cannot b.jar: a zlib decompression error was detected in the zip compressed data
(hang)


normal run:

wait_pipe_ready after wait
close_wait_zstream_open wait
wait_pipe_ready wait
wait_pipe_ready after wait
close_wait_zstream_open wait
join pipe_zstrm notify_one
↑↑↑↑↑↑(not block)
join pipe_zstrm after notify_one
join pipe_zstrm join
close_wait_zstream_open after wait
join pipe_zstrm after join
join pipe_zstrm notify_one
join pipe_zstrm after notify_one
join pipe_zstrm join
close_wait_zstream_open after wait
join pipe_zstrm after join
(exit program)
```

**Comment by genivia-inc** [comment]
OK. That's a more obvious problem to look into where the other end of the pipe is still open but no longer reading, probably because of an early termination on a zip error and/or when trying to recover from that error.

Both ends close each time a zip-compressed file is processed, then reopen a pipe for the next archive part to process until the entire zip was processed. Closing one end causes a broken pipe if data is pending and `write()` terminates with `< len` send, which is what we want in this case. The logic at ugrep.cpp:1284 skips files that are not selected to be searched (`is_selected`) and when we're not draining the input that should not be sent to the pipe (`!drain`).

This may seem complex to search zip files, but keep in mind we can handle nested zip this way and also skip over parts we don't want to search or that we cannot search. Tarballs are processed differently, where we just decompress them and then break up the stream of tar contents to search without using pipes and just `--zmax=1`. When tarballs are located inside zip, then the zip thread does the same thing to allow searching tarballs in zip (with `--zmax=2`).

**Comment by genivia-inc** [comment]
I noticed that the placement of the new "wake pipe_ready" may cause another issues, since the pipe fd is not -1 (not closed). It should be moved up to the begin of `start()`:
~~~
 reset pipe descriptors, pipe is closed
    pipe_fd[0] = -1;
    pipe_fd[1] = -1;

    // wake decompression thread waiting in wait_pipe_ready(), when it encountered an error
    if (thread.joinable() && waiting)
      pipe_ready.notify_one();
~~~
This still needs work though. I'm not 100% convinced that error recovery with nested zip can't cause problems down the pipe.

It would be great if you can share your `a.jar` and `b.jar` so I can replicate your observations then my tests are more complete. Testing with artificially introduced errors isn't great.

**Comment by mmyjona** [comment]
> I noticed that the placement of the new "wake pipe_ready" may cause another issues, since the pipe fd is not -1 (not closed). It should be moved up to the begin of `start()`:
> 
> ```
>  reset pipe descriptors, pipe is closed
>     pipe_fd[0] = -1;
>     pipe_fd[1] = -1;
> 
>     // wake decompression thread waiting in wait_pipe_ready(), when it encountered an error
>     if (thread.joinable() && waiting)
>       pipe_ready.notify_one();
> ```
> 
> This still needs work though. I'm not 100% convinced that error recovery with nested zip can't cause problems down the pipe.
> 
> It would be great if you can share your `a.jar` and `b.jar` so I can replicate your observations then my tests are more complete. Testing with artificially introduced errors isn't great.

I can confirm add if(waiting) to start() fix the hanging. Now the exception simply throw to the top and “libc++abi: terminating
” is outputted to the stderr

**Comment by genivia-inc** [comment]
This only addresses synchronization, not if a var is undefined leading to a crash. The path(s) on which that happens is not yet clear to me, which is harder to find without a debug trace that I can run myself. All pipe open/close calls should also be paired w/o double close (which will crash), which might be the issue here when threads get out of sync.

**Comment by genivia-inc** [comment]
OK, I've found the problem in the `Zthread::decompress()` logic flow when `--zmax` exceeds 1: the logic would jump out of a loop when nothing was decompressed (e.g. an error), which skipped over some code that causes the threads to de-synchronize. This de-synchronization can lead to all sorts of problems. The jump out of the loop is fine when `--zmax=1` (default). Since `--zmax` was added later, I had overlooked this as a potential problem that would occur when a zip or decompressor has an internal error.

The earlier suggested changes help, but those should not be needed when the threads run properly side-by-side.

Now, it is still early to cheer on success when there is still testing and analysis needed to make sure everything works like it should be. Testing negative cases (errors in the input) is always harder than testing correct input. I have to rely on creating "fake" negative test cases. However, with the clean logic I'm more confident that I don't have to generate a lot of "fake" negative test cases. We will see...

**Comment by genivia-inc** [comment]
I've committed my progress on this issue. Rolled back the previous changes to notify `pipe_ready` and instead updated `Zthread::decompress()` to perform the necessary state changes that were jumped over. Some minor (mostly cosmetic and for consistency) changes are included.
